/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as userRouteRouteImport } from './routes/(user)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as userSettingsRouteRouteImport } from './routes/(user)/settings/route'
import { Route as userAppRouteRouteImport } from './routes/(user)/app/route'
import { Route as userSettingsIndexRouteImport } from './routes/(user)/settings/index'
import { Route as userAppIndexRouteImport } from './routes/(user)/app/index'
import { Route as ApiUploadSplatRouteImport } from './routes/api/upload.$'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'
import { Route as userAppTodoRouteImport } from './routes/(user)/app/todo'
import { Route as userAppHelloFormRouteImport } from './routes/(user)/app/hello-form'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const userRouteRoute = userRouteRouteImport.update({
  id: '/(user)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => authRouteRoute,
} as any)
const userSettingsRouteRoute = userSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => userRouteRoute,
} as any)
const userAppRouteRoute = userAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => userRouteRoute,
} as any)
const userSettingsIndexRoute = userSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => userSettingsRouteRoute,
} as any)
const userAppIndexRoute = userAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => userAppRouteRoute,
} as any)
const ApiUploadSplatRoute = ApiUploadSplatRouteImport.update({
  id: '/api/upload/$',
  path: '/api/upload/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const userAppTodoRoute = userAppTodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => userAppRouteRoute,
} as any)
const userAppHelloFormRoute = userAppHelloFormRouteImport.update({
  id: '/hello-form',
  path: '/hello-form',
  getParentRoute: () => userAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof userAppRouteRouteWithChildren
  '/settings': typeof userSettingsRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/app/hello-form': typeof userAppHelloFormRoute
  '/app/todo': typeof userAppTodoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/upload/$': typeof ApiUploadSplatRoute
  '/app/': typeof userAppIndexRoute
  '/settings/': typeof userSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/signup': typeof authSignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin': typeof AdminIndexRoute
  '/app/hello-form': typeof userAppHelloFormRoute
  '/app/todo': typeof userAppTodoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/upload/$': typeof ApiUploadSplatRoute
  '/app': typeof userAppIndexRoute
  '/settings': typeof userSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)': typeof authRouteRouteWithChildren
  '/(user)': typeof userRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/(user)/app': typeof userAppRouteRouteWithChildren
  '/(user)/settings': typeof userSettingsRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/signup': typeof authSignupRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/': typeof AdminIndexRoute
  '/(user)/app/hello-form': typeof userAppHelloFormRoute
  '/(user)/app/todo': typeof userAppTodoRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/api/upload/$': typeof ApiUploadSplatRoute
  '/(user)/app/': typeof userAppIndexRoute
  '/(user)/settings/': typeof userSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/settings'
    | '/login'
    | '/signup'
    | '/admin/users'
    | '/admin/'
    | '/app/hello-form'
    | '/app/todo'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/upload/$'
    | '/app/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/admin/users'
    | '/admin'
    | '/app/hello-form'
    | '/app/todo'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/upload/$'
    | '/app'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/(auth)'
    | '/(user)'
    | '/admin'
    | '/(user)/app'
    | '/(user)/settings'
    | '/(auth)/login'
    | '/(auth)/signup'
    | '/admin/users'
    | '/admin/'
    | '/(user)/app/hello-form'
    | '/(user)/app/todo'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/api/upload/$'
    | '/(user)/app/'
    | '/(user)/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authRouteRoute: typeof authRouteRouteWithChildren
  userRouteRoute: typeof userRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
  ApiUploadSplatRoute: typeof ApiUploadSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(user)': {
      id: '/(user)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof userRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(user)/settings': {
      id: '/(user)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof userSettingsRouteRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(user)/app': {
      id: '/(user)/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof userAppRouteRouteImport
      parentRoute: typeof userRouteRoute
    }
    '/(user)/settings/': {
      id: '/(user)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof userSettingsIndexRouteImport
      parentRoute: typeof userSettingsRouteRoute
    }
    '/(user)/app/': {
      id: '/(user)/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof userAppIndexRouteImport
      parentRoute: typeof userAppRouteRoute
    }
    '/api/upload/$': {
      id: '/api/upload/$'
      path: '/api/upload/$'
      fullPath: '/api/upload/$'
      preLoaderRoute: typeof ApiUploadSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(user)/app/todo': {
      id: '/(user)/app/todo'
      path: '/todo'
      fullPath: '/app/todo'
      preLoaderRoute: typeof userAppTodoRouteImport
      parentRoute: typeof userAppRouteRoute
    }
    '/(user)/app/hello-form': {
      id: '/(user)/app/hello-form'
      path: '/hello-form'
      fullPath: '/app/hello-form'
      preLoaderRoute: typeof userAppHelloFormRouteImport
      parentRoute: typeof userAppRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authLoginRoute: typeof authLoginRoute
  authSignupRoute: typeof authSignupRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authLoginRoute: authLoginRoute,
  authSignupRoute: authSignupRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface userAppRouteRouteChildren {
  userAppHelloFormRoute: typeof userAppHelloFormRoute
  userAppTodoRoute: typeof userAppTodoRoute
  userAppIndexRoute: typeof userAppIndexRoute
}

const userAppRouteRouteChildren: userAppRouteRouteChildren = {
  userAppHelloFormRoute: userAppHelloFormRoute,
  userAppTodoRoute: userAppTodoRoute,
  userAppIndexRoute: userAppIndexRoute,
}

const userAppRouteRouteWithChildren = userAppRouteRoute._addFileChildren(
  userAppRouteRouteChildren,
)

interface userSettingsRouteRouteChildren {
  userSettingsIndexRoute: typeof userSettingsIndexRoute
}

const userSettingsRouteRouteChildren: userSettingsRouteRouteChildren = {
  userSettingsIndexRoute: userSettingsIndexRoute,
}

const userSettingsRouteRouteWithChildren =
  userSettingsRouteRoute._addFileChildren(userSettingsRouteRouteChildren)

interface userRouteRouteChildren {
  userAppRouteRoute: typeof userAppRouteRouteWithChildren
  userSettingsRouteRoute: typeof userSettingsRouteRouteWithChildren
}

const userRouteRouteChildren: userRouteRouteChildren = {
  userAppRouteRoute: userAppRouteRouteWithChildren,
  userSettingsRouteRoute: userSettingsRouteRouteWithChildren,
}

const userRouteRouteWithChildren = userRouteRoute._addFileChildren(
  userRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authRouteRoute: authRouteRouteWithChildren,
  userRouteRoute: userRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
  ApiUploadSplatRoute: ApiUploadSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
